### ISSUE TITLE
Data version is out-of-date

### ISSUE THREAD

**Issue by wzfhaha** [mims-harvard/G-Meta#3]
Dear authors,
    
    The provided dataset can not be loaded with the newest DGL version. Could you provide a new version of that?

**Comment by kexinhuang12345** [comment]
Hi, thanks for your interest in this project. please use the requirements.txt in the github in order to run the code. All the running scripts follow DGL 0.4.3post, so even if we change the dataset, the code would still not work. So the simple solution is to create a new virtual environment for this project using the requirements.txt.
